sudo: required

language: java

services:
  - docker

env:
  - JAVAVER="openjdk17"
  - JAVAVER="openjdk18"
  - JAVAVER="openjdk17-devel"
  - JAVAVER="openjdk18-devel"

before_install:
  - docker -v

install:
  - make BUILDARGS="--build-arg JAVAVER=$JAVAVER --build-arg USER_ID=$UID"

script:
  - ./runtest.sh
