sudo: required

language: java

services:
  - docker

env:
  - JAVAVER="oracle17"
  - JAVAVER="oracle18"
  - JAVAVER="openjdk17"
  - JAVAVER="openjdk18"
  - JAVAVER="openjdk17-devel"
  - JAVAVER="openjdk18-devel"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce 
  - docker -v

install:
  - make BUILDARGS="--build-arg JAVAVER=$JAVAVER --build-arg USER_ID=$UID"

script:
  - ./runtest.sh
